[package]
name = "wepd"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics-core = { version = "0.4.0", optional = true }
embedded-hal = "1.0.0"

[features]
default = ["embedded-graphics"]
embedded-graphics = ["dep:embedded-graphics-core"]
